[2022-05-30 19:28:30,256] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: lesson1.exercise4.list_keys manual__2022-05-30T19:28:28.842729+00:00 [queued]>
[2022-05-30 19:28:30,277] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: lesson1.exercise4.list_keys manual__2022-05-30T19:28:28.842729+00:00 [queued]>
[2022-05-30 19:28:30,277] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 19:28:30,278] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-05-30 19:28:30,278] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 19:28:30,291] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): list_keys> on 2022-05-30 19:28:28.842729+00:00
[2022-05-30 19:28:30,303] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'lesson1.exercise4', 'list_keys', 'manual__2022-05-30T19:28:28.842729+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launches.py', '--cfg-path', '/tmp/tmp4j9x0uf5', '--error-file', '/tmp/tmp7mw3v5mg']
[2022-05-30 19:28:30,304] {standard_task_runner.py:77} INFO - Job 7: Subtask list_keys
[2022-05-30 19:28:30,298] {standard_task_runner.py:52} INFO - Started process 12275 to run task
[2022-05-30 19:28:30,371] {logging_mixin.py:109} INFO - Running <TaskInstance: lesson1.exercise4.list_keys manual__2022-05-30T19:28:28.842729+00:00 [running]> on host b6b47ea722e0
[2022-05-30 19:28:30,460] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=lesson1.exercise4
AIRFLOW_CTX_TASK_ID=list_keys
AIRFLOW_CTX_EXECUTION_DATE=2022-05-30T19:28:28.842729+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-30T19:28:28.842729+00:00
[2022-05-30 19:28:30,487] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launches.py", line 28, in list_keys
    prefix = Variable.get('s3_prefix')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable s3_prefix does not exist'
[2022-05-30 19:28:30,513] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=lesson1.exercise4, task_id=list_keys, execution_date=20220530T192828, start_date=20220530T192830, end_date=20220530T192830
[2022-05-30 19:28:30,528] {standard_task_runner.py:91} ERROR - Failed to execute job 7 for task list_keys
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launches.py", line 28, in list_keys
    prefix = Variable.get('s3_prefix')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable s3_prefix does not exist'
[2022-05-30 19:28:30,564] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-30 19:28:30,598] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
