[2022-05-31 01:06:03,204] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: lesson1.exercise6.load_from_s3_to_redshift manual__2022-05-31T01:05:57.430912+00:00 [queued]>
[2022-05-31 01:06:03,219] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: lesson1.exercise6.load_from_s3_to_redshift manual__2022-05-31T01:05:57.430912+00:00 [queued]>
[2022-05-31 01:06:03,219] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 01:06:03,220] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-05-31 01:06:03,220] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-31 01:06:03,230] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_from_s3_to_redshift> on 2022-05-31 01:05:57.430912+00:00
[2022-05-31 01:06:03,238] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'lesson1.exercise6', 'load_from_s3_to_redshift', 'manual__2022-05-31T01:05:57.430912+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launches.py', '--cfg-path', '/tmp/tmpye59n4a1', '--error-file', '/tmp/tmp4ajpotrj']
[2022-05-31 01:06:03,239] {standard_task_runner.py:77} INFO - Job 11: Subtask load_from_s3_to_redshift
[2022-05-31 01:06:03,234] {standard_task_runner.py:52} INFO - Started process 28576 to run task
[2022-05-31 01:06:03,279] {logging_mixin.py:109} INFO - Running <TaskInstance: lesson1.exercise6.load_from_s3_to_redshift manual__2022-05-31T01:05:57.430912+00:00 [running]> on host b6b47ea722e0
[2022-05-31 01:06:03,323] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=lesson1.exercise6
AIRFLOW_CTX_TASK_ID=load_from_s3_to_redshift
AIRFLOW_CTX_EXECUTION_DATE=2022-05-31T01:05:57.430912+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-31T01:05:57.430912+00:00
[2022-05-31 01:06:03,324] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launches.py", line 17, in load_data_to_redshift
    aws_hook = AwsHook("aws_credentials")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 43, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 393, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2022-05-31 01:06:03,338] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=lesson1.exercise6, task_id=load_from_s3_to_redshift, execution_date=20220531T010557, start_date=20220531T010603, end_date=20220531T010603
[2022-05-31 01:06:03,350] {standard_task_runner.py:91} ERROR - Failed to execute job 11 for task load_from_s3_to_redshift
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launches.py", line 17, in load_data_to_redshift
    aws_hook = AwsHook("aws_credentials")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 43, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 393, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2022-05-31 01:06:03,374] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-31 01:06:03,410] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
