[2022-05-30 19:31:37,190] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: lesson1.exercise4.list_keys manual__2022-05-30T19:31:36.203609+00:00 [queued]>
[2022-05-30 19:31:37,212] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: lesson1.exercise4.list_keys manual__2022-05-30T19:31:36.203609+00:00 [queued]>
[2022-05-30 19:31:37,212] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 19:31:37,212] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-05-30 19:31:37,213] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-30 19:31:37,231] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): list_keys> on 2022-05-30 19:31:36.203609+00:00
[2022-05-30 19:31:37,242] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'lesson1.exercise4', 'list_keys', 'manual__2022-05-30T19:31:36.203609+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launches.py', '--cfg-path', '/tmp/tmp0kwjbkmq', '--error-file', '/tmp/tmpgdyhrmf7']
[2022-05-30 19:31:37,243] {standard_task_runner.py:77} INFO - Job 8: Subtask list_keys
[2022-05-30 19:31:37,238] {standard_task_runner.py:52} INFO - Started process 12429 to run task
[2022-05-30 19:31:37,303] {logging_mixin.py:109} INFO - Running <TaskInstance: lesson1.exercise4.list_keys manual__2022-05-30T19:31:36.203609+00:00 [running]> on host b6b47ea722e0
[2022-05-30 19:31:37,361] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=lesson1.exercise4
AIRFLOW_CTX_TASK_ID=list_keys
AIRFLOW_CTX_EXECUTION_DATE=2022-05-30T19:31:36.203609+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-30T19:31:36.203609+00:00
[2022-05-30 19:31:37,385] {rocket_launches.py:29} INFO - Listing Keys from s3://udacity-dend/udac-data-pipelines/divvy//data-pipelines
[2022-05-30 19:31:37,386] {base_aws.py:401} INFO - Airflow Connection: aws_conn_id=aws_credentials
[2022-05-30 19:31:37,396] {base_aws.py:177} INFO - Credentials retrieved from login
[2022-05-30 19:31:37,396] {base_aws.py:93} INFO - Creating session with aws_access_key_id=AKIAWLZI7S5RULXYYBHS region_name=None
[2022-05-30 19:31:37,411] {base_aws.py:168} INFO - role_arn is None
[2022-05-30 19:31:37,414] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/providers/amazon/aws/hooks/base_aws.py:494: DeprecationWarning: client_type is deprecated. Set client_type from class attribute.
  return self.get_client_type(self.client_type, region_name=self.region_name)

[2022-05-30 19:31:37,561] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launches.py", line 30, in list_keys
    keys = hook.list_keys(bucket, prefix=prefix)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 62, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 301, in list_keys
    for page in response:
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/paginate.py", line 334, in _make_request
    return self._method(**current_kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/client.py", line 681, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/client.py", line 727, in _convert_to_request_dict
    api_params, operation_model, context)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/client.py", line 759, in _emit_api_params
    params=api_params, model=operation_model, context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/handlers.py", line 243, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "s3://udacity-dend/udac-data-pipelines/divvy/": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
[2022-05-30 19:31:37,579] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=lesson1.exercise4, task_id=list_keys, execution_date=20220530T193136, start_date=20220530T193137, end_date=20220530T193137
[2022-05-30 19:31:37,597] {standard_task_runner.py:91} ERROR - Failed to execute job 8 for task list_keys
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launches.py", line 30, in list_keys
    keys = hook.list_keys(bucket, prefix=prefix)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 62, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 301, in list_keys
    for page in response:
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/paginate.py", line 334, in _make_request
    return self._method(**current_kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/client.py", line 681, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/client.py", line 727, in _convert_to_request_dict
    api_params, operation_model, context)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/client.py", line 759, in _emit_api_params
    params=api_params, model=operation_model, context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/handlers.py", line 243, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "s3://udacity-dend/udac-data-pipelines/divvy/": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
[2022-05-30 19:31:37,622] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-30 19:31:37,663] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
